#!/bin/bash
set -e

cd ~/.vim_runtime

cd my_plugins/YouCompleteMe
python install.py --all
python install.py --clang-completer
python install.py --clangd-completer
cd ~/.vim_runtime

if [ -d "~/.vim" ];then
    rm -rf ~/.vim
fi

cp -r .vim_files ~/.vim

if [ -e "~/.tmux.conf" ];then
    rm ~/.tmux.conf
fi

cp .tmux.conf ~/.tmux.conf

if [ -z 'grep "LS_COLORS" ~/.bashrc' ]; then
    echo "LS_COLORS=$LS_COLORS:'tw=00;33:ow=01;33:'; export LS_COLORS" >> ~/.bashrc
fi

if [ -z 'grep "TERM=" ~/.bashrc' ]; then
    echo 'export TERM="xterm-256color"' >> ~/.bashrc
fi

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry' > ~/.vimrc

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
