#!/bin/bash
set -e
cd ~

if [ ! -d ~/.vim_runtime/backup ]; then
    mkdir ~/.vim_runtime/backup
fi

#tmux config setting
if [ -e ~/.tmux.conf ]; then
    mv ~/.tmux.conf ~/.vim_runtime/backup
fi

if [ -e ~/.tmux.conf.local ]; then
    mv ~/.tmux.conf.local ~/.vim_runtime/backup
fi

ln -s ~/.vim_runtime/tmux_config/.tmux.conf
ln -s ~/.vim_runtime/tmux_config/.tmux.conf.local

echo "Installed the Awesome TMUX configuration successfully! Enjoy :-)"

#color bash
if [ -e ~/.bashrc ]; then
    cp ~/.bashrc ~/.vim_runtime/backup
fi

echo "source ~/.vim_runtime/my_bashrc" >> ~/.bashrc

if [ -e ~/.vimrc ]; then
    mv ~/.vimrc ~/.vim_runtime/backup
fi

echo "Installed the bashrc successfully! Enjoy :-)"

#vim configuration
echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry' > ~/.vimrc

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
